import { Grid, Typography } from '@mui/material'
import { Box } from '@mui/system'
import Head from 'next/head'
import React from 'react'
import CardAddCostumer from '../components/Card/CardAddData'
import Header from '../components/Header'
import MiniDrawer from '../components/Header/header'
// import styles from '../styles/Home.module.css'

export default function AddCostumer () {
  return (
    <>
      <Head>
        <title>Admin Dashboard | Add Costumer</title>
        <meta name="description" content="Generated by Admin Dashboard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container >
        <Grid item>
          {/* <Header /> */}
          <MiniDrawer />
        </Grid>

        <Grid item sx={{ml : 30, mt : 5}}>
          <Box sx={{m : 3, p : 3}}>
            <Typography component='div' sx={{fontWeight : 'bold', mb : 4}} variant='h6'>
              Add Product 
            </Typography>

            <Box>
              <CardAddCostumer />
            </Box>

          </Box>

        </Grid>
      </Grid>
        
    </>
  )
}
