import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import { Box, Grid, Typography } from '@mui/material'
import Card1 from '../components/Card/card1'
import Card2 from '../components/Card/card2'
import Card3 from '../components/Card/card3'
import Costumer from '../components/Costumer/costumer'
import MiniDrawer from '../components/Header/header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Dashboard | Home Page</title>
        <meta name="description" content="Generated by Admin Dashboard" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        <Grid item>
          {/* <Header /> */}
          <MiniDrawer />
        </Grid>

        <Grid item sx={{mt : 5}}>
          <Box>
            <Typography component='div' sx={{fontWeight : 'bold', mb : 3, mt : 5}} variant='h6'>
              Dashboard
            </Typography>
            <Box sx={{mt : 3, py : 3}} >
              

              <Grid container spacing={2}>
                <Grid item xs={3}>
                  <Card1 />
                </Grid>
                <Grid item xs={3}>
                  <Card2 />
                </Grid>
                <Grid item xs={3}>
                  <Card3 />
                </Grid>
                <Grid item xs={3}>
                  <Card3 />
                </Grid>
              </Grid>
            </Box>
            <Box sx={{my : 3, py : 3}}>
              <Costumer />
            </Box>
          </Box>

        </Grid>
      </Grid>      
    </div>
  )
}

export default Home
